### ISSUE TITLE
Update Pypi

### ISSUE THREAD

**Issue by Mazyod** [qba73/circleclient#5]
Hello,

Thanks for taking the time to put this together!
I installed the package, but it doesn't seem to have the filter parameter introduced in #4. Is it possible to update the package?

Thanks again,
Maz

**Comment by qba73** [comment]
Hi, I will be doing release this weekend. The new package should be in Pypi by Monday.
Cheers,
Jakub

**Comment by qba73** [comment]
@Mazyod @diN0bot @JasonBoyles release 0.1.5 with filtering uploaded to pypi: https://pypi.python.org/pypi/circleclient/0.1.5
many thanks for contributing!
